### PR TITLE
Bump wallaby

### PR DESCRIPTION
**Pull request by Zanadar**
**NOTE**: This bump will generate a ton of warnings.  I'll address those in a followup PR.
Gives us some nice new features in the API

### CODE REVIEW

**Comment by vanderhoop** [comment]
hey @Zanadar. this looks great, but the warnings make the test output kinda verbose, especially for anyone new to the project. Address the warnings and we'll get this in!

**Comment by Zanadar** [comment]
Okay, whacked these down.  Onward and upward!

**Comment by vanderhoopnbc** [comment]
woot, merging

**Comment by vanderhoop** [comment]
looks good, merging!

**Pull request merged**
